### ISSUE TITLE
Reduction is not stored on disk

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#106]
When setting the default values and their attribute values and you save and close the application, after reloading the project these configurations aren't strored.

**Comment by ujrlh** [comment]
Please describe the use case more detailed, because when i tested it, it works.

**Comment by GloeStoe** [comment]
Reproduce this by:
- Create new project
- Go to default settings.
- Select tag default (it is selected by default)
- Type non-zero values into the fields 'Area', 'Number of Fllors' and 'Floor Area'
- Save
- close the app
- open the project again
- go to the default settings

The entered values are now 0 again
