### ISSUE TITLE
Aggregation Frame not working

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#109]
There are no aggregation methods listed at the Aggregation Frame

**Comment by LuposX** [comment]
![Screenshot from 2023-02-22 14-03-08](https://user-images.githubusercontent.com/36456825/220627279-af19da3c-9961-4eae-a524-af4c3fefc3a0.png)


There are @GloeStoe

**Comment by GloeStoe** [comment]
True
