### ISSUE TITLE
When trying to deactivate the standard "Gebäude" category pop is shown

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#113]
Trying to deactivate the standard category is not possible.

https://user-images.githubusercontent.com/36456825/220386339-940293f5-13d1-4be9-b63f-ead283472848.mp4

**Comment by LuposX** [comment]
This happens with every category

**Comment by calliminator** [comment]
fixxed, category never returned if activatin or disabling worked, and view expected an answer wich it nerver got
