### ISSUE TITLE
Bad color choice for checkboxes and co.

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#117]
Example: Unchecked checkboxes are invisible, because they have the same color as the background.

**Comment by LuposX** [comment]
Example, export:

![Screenshot from 2023-02-21 18-49-33](https://user-images.githubusercontent.com/36456825/220421660-b82493fb-ea26-4b32-b4b2-916a5572f133.png)

**Comment by FelixWeik** [comment]
Issue fixed in latest commit
