### ISSUE TITLE
Infinity many popups when pressing button in calulate frame

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#118]
When pressing a button in the caulatio nframe and its not valid it creates apopup, there can be infinity many of them.

https://user-images.githubusercontent.com/36456825/220388820-68922918-2d39-49e9-a742-0ac374913e1c.mp4

**Comment by GloeStoe** [comment]
see also #111

**Comment by GloeStoe** [comment]
done, even tho there are still other mistakes in the calcualtions.
-> These other errors will be addressed in other issues
