### ISSUE TITLE
The button "strictly use default values" works opposite

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#120]
Only if the button "strictly use default values" in the Reduction Frame is activated will it allow to other settings to be enabled, but it should be the opposite, settings should be allowed to make when  "strictly use default values" is NOT activated.

![image](https://user-images.githubusercontent.com/36456825/220390541-be824123-7911-4e00-962c-9beab3d57968.png)
![image](https://user-images.githubusercontent.com/36456825/220390571-bf663031-59f0-4399-a3c0-36770a64dbd6.png)

**Comment by GloeStoe** [comment]
it seems like the ckebox doesn't activates/deactivates the checkboxes below at all now

**Comment by LuposX** [comment]
The problem is in the reduction_cclauclatrion_frame

**Comment by LuposX** [comment]
issuse is agan there

**Comment by calliminator** [comment]
"fix" reverted
