### ISSUE TITLE
Application Settings File does not work

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#129]
When setting the default folder the application_settings.json looks like that:
![grafik](https://user-images.githubusercontent.com/26413947/220404459-dbc97505-cd97-4cc3-b5d0-0696452e88e9.png)

After restarting the app the settings allways look like that (independent of what they were before):
![grafik](https://user-images.githubusercontent.com/26413947/220404083-b4310e59-fa0d-412f-bc5a-d3a7e8eccb8a.png)

Hint: You have to be on a brnach that implemented teh fixes of fix_settings_default_folder, to observe this behaviour.

**Comment by LuposX** [comment]
Is this only on "fix_settings_default_folder" because if you did sth. worng, how should I know what you changed that make this break @GloeStoe ?

**Comment by LuposX** [comment]
Und der Step-To-Step Guide ist:
- Lade/Create ein Projekt
- Gehe in die Settings rein
- Wähle einen neuen Default folder aus
- Schaue dir die ApplicationSettings.json an

**Comment by LuposX** [comment]
fixed first part of the issue
