### ISSUE TITLE
When using the button "load external projects" error is thrown

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#131]
When trying to load an etxernal project from the main menu and then closing the menu an error is thrown

https://user-images.githubusercontent.com/36456825/220405071-ad7f1eae-ebc5-462b-ac90-1807867b17c5.mp4

**Comment by GloeStoe** [comment]
doesn't happen for me

**Comment by GloeStoe** [comment]
was fixed with another issue
