### ISSUE TITLE
Cancel button in Calculation does not work

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#153]
When pressing the cancel button (calculation Frame) an error accures.

**Comment by LuposX** [comment]
https://user-images.githubusercontent.com/36456825/220608847-58598824-28c7-40c9-ba2f-0f2c2fe4e801.mp4



Works for me, but its stuck and doesn't claculate anything, stuck in endless loop.

**Comment by GloeStoe** [comment]
fixed
