### ISSUE TITLE
Calculation Fails at Rare Input Combination

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#175]
Reproduce by:
- Go to the calculation frame
- Start a calculation
- Press the cancel button immediatly
- Don't confirm the cancelation
- Wait until the calculation stops wit an error
- Now confirm the calculation

hen an error accures

**Comment by calliminator** [comment]
The PopUp asking to stop the calculation is now saved as a private attribute, so if the calculation stops by itself, it will destroy the YesNoPop up aswell (if it exists), making the bug impossible.
