### ISSUE TITLE
View doesn't realize Aggregation is finished

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#181]
Aggregation is finished calculating, you can see this by checking the result folder, but view still says it's calculating.

https://user-images.githubusercontent.com/36456825/220732174-ecd1c224-5f63-41d0-aa12-961258a92b36.mp4

**Comment by GloeStoe** [comment]
waiting for #190 to be solved.

**Comment by GloeStoe** [comment]
fixed
