### ISSUE TITLE
strictyl use default values is rewersed, it closes editing when activated, rather when disabled

### ISSUE THREAD

**Issue by calliminator** [LuposX/KonfiguratorFuerOSMDaten#209]
Go to Reduction Calculation sub frame.
When selecting the stricly use default values it will disabled editing when checked. That should happen when it is unchecked

**Comment by LuposX** [comment]
This is false @calliminator #120 i am gonna close this.

**Comment by calliminator** [comment]
no it is a bug, reduction doesn't enables/disabled checkboxes properly

**Comment by calliminator** [comment]
fixxed it now
