### ISSUE TITLE
Calcualtion button are only siabled when creating a project/ctageory

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#213]
when laoding a project than the buttons in the caluclation frame which should be disbaled are not diabled.

![Screenshot from 2023-02-23 11-28-00](https://user-images.githubusercontent.com/36456825/220881543-c707a5d9-3867-4508-9f80-4c278c31b301.png)

**Comment by calliminator** [comment]
should be fixxed
