### ISSUE TITLE
Default Values Switching does not work

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#233]
1. Create a new project
2. Add 2 default values to the category 'Building'
3. Switch them arround with the arrows
4. Now try selecting other default values

Now the selection of the default valeu entries does no longer work

**Comment by ujrlh** [comment]
You can select other default value tags but it seems that the shown list isnt synced with the internal list:
1. Create tag1, tag2, tag3
2. Move tag1 to the bottom of the list
3. Select tag1 in the list
Now the view will display details on tag2 (because it is on the postion, tag1 was before)

**Comment by calliminator** [comment]
fixxed, also fixxed that default value can't be name changed, and the frame freezes properly when an yes_no_pop_up comes up.
