### ISSUE TITLE
page break in the settings

### ISSUE THREAD

**Issue by ujrlh** [LuposX/KonfiguratorFuerOSMDaten#252]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/118002267/221422601-bf97c5da-a618-48cb-b37e-1aaec704e4ba.png">

The whole word "calculation" should be in the second row.

**Comment by calliminator** [comment]
well if you type it in that way, the ofcourse it will be seperated, this is more of a tkinter thing, as if you just type words and it reaches the end of the textbox, it will just keep writing on the next row. It will not "interpretieren" it as a row break, for example if the textbox was larger the whole word would be there standing and not randomly break in the middle.

**Comment by GloeStoe** [comment]
![grafik](https://user-images.githubusercontent.com/26413947/224740910-3a9f8821-9013-4a22-bfed-56d118d70c96.png)
There is a option for wraping text
https://github.com/TomSchimansky/CustomTkinter/wiki/CTkTextbox
