### ISSUE TITLE
"Copy in Category Configuration": File dialog expects file

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#258]
When trying to import categories on the "Data" frame, the user is expected to enter a file, but he needs to enter a folder

**Comment by FelixWeik** [comment]
Are there any expected data-types (like .geojson, .json, .csv, ...)?

**Comment by GloeStoe** [comment]
so there are no expected data-types except the "folder-Datatype"

**Comment by FelixWeik** [comment]
Solved issue in latest merge, data frame accepts only directories now instead of files

**Comment by GloeStoe** [comment]
see pull request

**Comment by GloeStoe** [comment]
I removed you as an assingee, so we don't document this error twice
