### ISSUE TITLE
Canceling Calculation causes errors

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#283]
![grafik](https://user-images.githubusercontent.com/26413947/223804921-998c7ce3-eaa4-4d95-8bce-39f15bcc8b07.png)

**Comment by GloeStoe** [comment]
I am not able to fix this

**Comment by LuposX** [comment]
We dont know what is happen ign here, but when the pallicatio nis an exe it doesnt matter.
