### ISSUE TITLE
Attrativityphase: No object in category

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#285]
When there is no OSM-object in a category, the attractivity phase removes all attractivity attributes of that category.
But the aggregation phase expects there to be a column for every attractivity attribute. his causes an error

**Comment by GloeStoe** [comment]
Fixed by adding a final line filled with Nan's

**Comment by LuposX** [comment]
Dont just close it, only close it after you merged it to the "main" or "dev" branch.

**Comment by GloeStoe** [comment]
very funny
