### ISSUE TITLE
bz2 File format is not supported

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#293]
When selecting a osm file in the bz2 format as data input, you get an error in the geodataphase.

**Comment by LuposX** [comment]
@GloeStoe can you check that out, try the andorra osm file(in bz2 format) in the data folder.

**Comment by GloeStoe** [comment]
It works for me. I don't get an error. I gett thi spop up:
![grafik](https://user-images.githubusercontent.com/26413947/224735591-4d08c58e-fbf8-4170-b37b-439843bdf3a0.png)

Maybe I could make it a little bit more descriptive like "The format .bz2 is not supported"

**Comment by LuposX** [comment]
- remove bz2 data from dofler
- write somehwere that we dont support that

**Comment by GloeStoe** [comment]
fixed
