### ISSUE TITLE
A default attractivity doesn't exist anymore.

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#294]
It used to be that we had a default attractivity when creating a project, this doesn't exist anymore. We should add it back in.
![Screenshot from 2023-03-11 13-10-57](https://user-images.githubusercontent.com/36456825/224483665-a644f8f8-c40e-4081-bb7a-8e993edb235d.png)

**Comment by LuposX** [comment]
@ujrlh can you check this out?

**Comment by GloeStoe** [comment]
I do not remember there to be a default attractivity and I don't think we specified oen in any of our artefacts. I think a default attractivity is not necessary

**Comment by ujrlh** [comment]
Karl is right, we never had a default attractivity. Thats whats causes bug #251
