### ISSUE TITLE
Creating a project fails: when cancling the "choose destination" button

### ISSUE THREAD

**Issue by LuposX** [LuposX/KonfiguratorFuerOSMDaten#305]
When creating a project and licking the button "choose destination" and then pressing cancle you get the following error message:
![image](https://user-images.githubusercontent.com/36456825/224545124-990a98d0-0aef-43f9-832f-257b36473d71.png)

**Comment by LuposX** [comment]
#304 should fix this

**Comment by GloeStoe** [comment]
The error is not caused by canceling the file dialog, but by the fact that when opening the data frame it is checked, whether the geodata-file exists. Because when creation an new project, the file path is None, there is allways an error when creating a new project.

**Comment by GloeStoe** [comment]
@ujrlh fixes this together with other bugs
