### ISSUE TITLE
weird errors when using aggregation phase in exe

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/KonfiguratorFuerOSMDaten#355]
I get the following errors:

![grafik](https://user-images.githubusercontent.com/26413947/225699366-f8b23e9a-b22e-4b08-84f0-643c65d8fc4d.png)

**Comment by GloeStoe** [comment]
Reproduce by 
1. starting the exe
2. Loading a correctly configured project
3. run the calculation fully
4. now run the calculation starting in the aggregation phase

**Comment by LuposX** [comment]
same as #356
